# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountModel',
            fields=[
                ('idAccounts', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=30)),
                ('money', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='BankModel',
            fields=[
                ('idBanks', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=16)),
                ('comments', models.CharField(max_length=1000)),
            ],
            options={
                'db_table': 'banks',
            },
        ),
        migrations.CreateModel(
            name='CustomerModel',
            fields=[
                ('idCustomer', models.AutoField(primary_key=True, serialize=False)),
                ('fio', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=45, unique=True)),
                ('password', models.CharField(max_length=45)),
                ('phone', models.CharField(max_length=16, unique=True)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='bankId_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.BankModel'),
        ),
        migrations.AddField(
            model_name='accountmodel',
            name='customerId_FK',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CustomerModel'),
        ),
    ]
