# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 08:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionsModel',
            fields=[
                ('idTransactions', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.IntegerField()),
                ('currency', models.CharField(max_length=10)),
                ('comments', models.CharField(max_length=100)),
                ('time_t', models.DateField()),
            ],
            options={
                'db_table': 'transactions',
            },
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='bankId_FK',
            field=models.ForeignKey(db_column='bankId_FK', on_delete=django.db.models.deletion.CASCADE, to='myapp.BankModel'),
        ),
        migrations.AlterField(
            model_name='accountmodel',
            name='customerId_FK',
            field=models.ForeignKey(db_column='customerId_FK', on_delete=django.db.models.deletion.CASCADE, to='myapp.CustomerModel'),
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='accountId_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountId_from', to='myapp.AccountModel'),
        ),
        migrations.AddField(
            model_name='transactionsmodel',
            name='accountId_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accountId_to', to='myapp.AccountModel'),
        ),
    ]
