# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-27 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20171227_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionsmodel',
            name='time_t',
            field=models.DateTimeField(),
        ),
    ]
