# Generated by Django 2.0 on 2018-01-07 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_auto_20171227_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankmodel',
            name='image',
            field=models.ImageField(default='static/img/banks/default.jpg', upload_to='static/img/banks'),
        ),
        migrations.AddField(
            model_name='bankmodel',
            name='short_comments',
            field=models.CharField(default='TODO', max_length=500),
        ),
        migrations.AlterField(
            model_name='transactionsmodel',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
