# Generated by Django 2.0 on 2018-01-08 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20180108_0313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankmodel',
            name='image',
            field=models.ImageField(default='banks/default.jpg', upload_to='banks'),
        ),
    ]
